
export const REQUEST_GET_MUSIC = 'REQUEST_GET_MUSIC';
export const GET_MUSIC_SUCCESS = 'GET_MUSIC_SUCCESS';
export const GET_MUSIC_FAIL = 'GET_MUSIC_FAIL';
export const GET_LIST_MUSIC = 'GET_LIST_MUSIC';
export const POST_EDIT_MUSIC = 'REQUEST_POST_EDIT_MUSIC';
export const UPDATE_STORE_MUSIC_TMP = 'UPDATE_STORE_MUSIC_TMP';
export const POST_EDIT_MUSIC_SUCCESS = 'REQUEST_POST_EDIT_MUSIC_SUCCESS';
export const POST_EDIT_MUSIC_FAIL = 'REQUEST_POST_EDIT_MUSIC_FAIL';
export const POST_DELETE_MUSIC = 'REQUEST_POST_DELETE_MUSIC';
export const POST_DELETE_MUSIC_SUCCESS = 'REQUEST_POST_DELETE_MUSIC_SUCCESS';
export const POST_DELETE_MUSIC_FAIL = 'REQUEST_POST_DELETE_MUSIC_FAIL';

// Get
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAIL = 'GET_LIST_FAIL';
export const GET_LIST = 'GET_LIST';
// edit
export const UPDATE_STORE_TMP = 'UPDATE_STORE_TMP';


export const GET_CURRENT = 'GET_CURRENT';
export const GET_PARENT = 'GET_PARENT';

//
export const GET_USED_MEMORY = 'GET_USED_MEMORY';
